[workspace]
members = [
    "node",
    "pallets/identity_pallet",
    "pallets/proof_of_existence",
    "pallets/crypto_kitties",
    "pallets/quadratic_voting",
    "runtime",
]
[profile.release]
panic = "unwind"
